config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  devise_for :users, controllers: { registrations: 'users/registrations' , omniauth_callbacks: 'users/omniauth_callbacks'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :concerts
  post 'concerts/:id', to: 'concerts#reload'
  mount ActionCable.server, at: '/cable'
  resources :chatrooms, param: :slug # slug only change the default :id to :slug, value doesn't change
  resources :messages
  get "users/:id", to: "users#show", as: "users"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_and_belongs_to_many :concerts

  mount_uploader :avatar, AvatarUploader
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages, class_name: "Message", dependent: :destroy
  has_many :user, through: :messages
  belongs_to :concert
end

app/models/city.rb
class City < ApplicationRecord
  has_many :concerts
end

app/models/concert.rb
class Concert < ApplicationRecord
  has_and_belongs_to_many :artists
  has_and_belongs_to_many :users
  belongs_to :city
  has_many :chatrooms
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/search.rb
class Search < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_and_belongs_to_many :concerts
  has_many :messages
  has_many :chatrooms, through: :messages
  validates :first_name, presence: true
  validates :last_name, presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook google_oauth2]

  mount_uploader :avatar, AvatarUploader

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
    end
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  def show
    @artists = Artist.find(params[:id])
  end

end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  # def index
  #   @chatrooms = Chatroom.paginate(page: params[:page], per_page: 5)
  # end
  #
  # def new
  #   @chatroom = Chatroom.new
  # end
  #
  # def create
  #   @chatroom = Chatroom.new(chatroom_params)
  #   if @chatroom.save
  #     respond_to do |format|
  #       format.html { redirect_to @chatroom }
  #       format.js
  #     end
  #   else
  #     respond_to do |format|
  #       flash[:notice] = {error: ["a chatroom with this topic already exists"]}
  #       format.html { redirect_to new_chatroom_path }
  #       format.js { render template: 'chatrooms/chatroom_error.js.erb'}
  #     end
  #   end
  # end
  #
  # def show
  #   @chatroom = Chatroom.find_by(id: params[:slug])
  #   @message = Message.new
  # end
  #
  # private
  #
  # def chatroom_params
  #   params.require(:chatroom).permit(:topic)
  # end

    def index
      @chatrooms = Chatroom.paginate(page: params[:page], per_page: 5)
    end

    def show
      @chatroom = Chatroom.find_by(id: params[:slug])
      @message = Message.new
    end
end

app/controllers/concerts_controller.rb
require 'net/http'
require 'json'

class ConcertsController < ApplicationController
  def index
  end

  def create # s'inscrire depuis une page concert
    concert = Concert.find_or_initialize_by(soundkick_id: params[:soundkick_id])
    concert.date = Date.parse(params[:date]).iso8601
    concert.city = City.find_by(metro_area_songkick_id: params[:city])
    concert.soundkick_id = params[:soundkick_id]
    concert.title = params[:concert_title]
    concert.save
    if !concert.users.exists?(current_user.id)
      concert.users << User.find(current_user.id)
    end
    if !concert.chatrooms.exists?
      list_topic = ["Before","Trajet, covoiturage...","Discussion : les vrais savent","Debrief"]
      list_topic.each do |topic|
        chat = Chatroom.new
        chat.topic = topic
        chat.soundkick_id = params[:soundkick_id]
        chat.concert_id = concert.id
        chat.stage = 1
        chat.save
      end
    end
    redirect_to concert_path(concert.soundkick_id)
  end

  def reload
    current_user.concerts.delete(Concert.find_by(soundkick_id: params[:id]))
    redirect_to concert_path(params[:id])
  end

  def show
    @event_id = params[:id]
    if Concert.exists?(soundkick_id: params[:id])
      @concert = Concert.find_by(soundkick_id: params[:id])
      @interested_number = @concert.users.all.length
      @concert_exist = true
      if user_signed_in?
        @inscrit = @concert.users.exists?(current_user.id)
      end
    end
    resulte = JSON.parse(Net::HTTP.get(URI.parse("https://api.songkick.com/api/3.0/events/#{@event_id}.json?apikey="+ Rails.application.credentials.dig(:songkick_api))))
    result = resulte["resultsPage"]["results"]["event"]
    @artist_name = result["performance"][0]["displayName"]
    @venue_place = result["venue"]["displayName"]
    @venue_adress = result["venue"]["street"]
    @venue_postal_code = result["venue"]["zip"]
    @venue_city = result ["venue"]["city"]["displayName"]
    @venue_city_id = result["venue"]["city"]["id"]
    @venue_date = result["start"]["date"]
    @venue_hour = result["start"]["time"]
    @concert_url = result["uri"]
    @concert_name = result["displayName"]
    @sentences = ["Organisez vos before pour faire connaissance", "Trouvez d'autres personnes pour effectuer votre trajet", "Les top album, les dernières infos, les clash... Les vrais savent.", "Partagez vos souvenirs et impressions post-concert"]
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    message = Message.new(message_params)
    message.user = current_user
    if message.save
      ActionCable.server.broadcast 'messages',
        message: message.content,
        user: message.user.first_name,
        chatroom_id: message.chatroom_id
      head :ok
    else
      redirect_to chatrooms_path
    end
  end

  private
    def message_params
      params.require(:message).permit(:content, :chatroom_id)
    end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def new
    @search = Search.new
    @cities = Concert.uniq.pluck(:city)
  end

  def create
      @search = Search.create(search_params)
      redirect_to @search
  end

  def show
      @search = Search.find(params[:id])
  end


  private

  def search_params
      params.require(:search).permit(:title, :city)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/concert_helper.rb
module ConcertHelper
  def artiste_show(search_artist)
    require 'net/http'
    require 'json'
    result = JSON.parse(Net::HTTP.get(URI.parse("https://api.songkick.com/api/3.0/events.json?&artiste_name=" + search_artist + "&location=sk:28909&apikey=" + Rails.application.credentials.dig(:songkick_api) + "&per_page=100&page=" + (i + 1).to_s)))["resultsPage"]["results"]["event"]
    result.each { |key|
      hash = {}
      hash["titre"] = key["displayName"].downcase
      hash["date"] = key["start"]["date"].downcase
      hash["ville"] = key["location"]["city"].downcase
      hash["lieu"] = key["venue"]["displayName"].downcase
      hash["url"] = key["uri"]
      array_artiste = []
      key["performance"].each { |performance|
        array_artiste << performance["displayName"].downcase
      }

      hash["artistes"] = array_artiste

      test.push(hash)
    }
    return test
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
  def markdown_to_html(text)
    Kramdown::Document.new(text, input: 'GFM').to_html
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_flash_errors.html.erb
<% if flash.notice %>
  <div class="alert alert-danger">
      <% flash.notice.each do |type, messages|%>
        <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span><%messages.each do |msg|%>
          <%=type%> <%=msg%>
        <%end%>
      <%end%>
  </div>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Live & Tribe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    

    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">


    <script src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>


    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/instantsearch.js@2.3/dist/instantsearch.min.css">
    <% if user_signed_in? %>
      <%= tag :meta, name: "current-user", data: {id: current_user.id} %>
    <% end %>
  </head>

  <body>

    <%= yield %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script id="dsq-count-scr" src="//live-tribe.disqus.com/count.js" async></script>
  </body>
</html>

app/views/shared/_bysoundkick.html.erb
<%= image_tag("powered-by-songkick-white.png", class:'img-fluid soundkick-footer', width: '200px', style: "padding-bottom:40px") %>

app/views/shared/_footer.html.erb
<section id="footer">
		<div class="container">
			<div class="row text-center text-xs-center text-sm-left text-md-left">
				<div class="col-xs-12 col-sm-4 col-md-4 columns-footer">
					<h5 class="footer-title ">Villes</h5>
					<ul class="list-unstyled quick-links">
						<li><a href="/concerts?q=Paris&hPP=12&idx=ParisConcerts&p=0"><i class="fa fa-angle-double-right"></i>Paris</a></li>
						<li><a href="/concerts?q=Lyon&hPP=12&idx=ParisConcerts&p=0"><i class="fa fa-angle-double-right"></i>Lyon</a></li>
						<li><a href="/concerts?q=Marseille&hPP=12&idx=ParisConcerts&p=0"><i class="fa fa-angle-double-right"></i>Marseille</a></li>
						<li><a href="/concerts?q=Toulouse&hPP=12&idx=ParisConcerts&p=0"><i class="fa fa-angle-double-right"></i>Toulouse</a></li>
						<li><a href="/concerts?q=Bordeaux&hPP=12&idx=ParisConcerts&p=0"><i class="fa fa-angle-double-right"></i>Bordeaux</a></li>
						<li><a href="/concerts?q=Lille&hPP=12&idx=ParisConcerts&p=0"><i class="fa fa-angle-double-right"></i>Lille</a></li>
						<li><a href="/concerts?q=Nice&hPP=12&idx=ParisConcerts&p=0"><i class="fa fa-angle-double-right"></i>Nice</a></li>
						<li><a href="/concerts?q=Nantes&hPP=12&idx=ParisConcerts&p=0"><i class="fa fa-angle-double-right"></i>Nantes</a></li>
						<li><a href="/concerts?q=Starsbourg&hPP=12&idx=ParisConcerts&p=0"><i class="fa fa-angle-double-right"></i>Strasbourg</a></li>
						<li><a href="/concerts?q=Rennes&hPP=12&idx=ParisConcerts&p=0"><i class="fa fa-angle-double-right"></i>Rennes</a></li>
					</ul>
				</div>
				<div class="col-xs-12 col-sm-4 col-md-4 colums-footer">
					<h5 class="footer-title">Live & Tribe</h5>
					<ul class="list-unstyled quick-links">
						<li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>À propos</a></li>
						<li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>Contact</a></li>
						<li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>FAQ</a></li>
						<li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>Notre Histoire</a></li>
						<li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>Videos</a></li>
					</ul>
				</div>
				<div class="col-xs-12 col-sm-4 col-md-4 img-fluid img-footer">
					<%= render 'shared/bysoundkick' %>
					<br>
					<%= render 'shared/search_by_algolia' %>
				</div>

			</div>
     </hr>
			<div class="row">
				<div class="social-logos col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-5">
					<ul class="list-unstyled list-inline social text-center">
						<li class="list-inline-item"><a href="javascript:void();"><i class="fa fa-facebook"></i></a></li>
						<li class="list-inline-item"><a href="javascript:void();"><i class="fa fa-twitter"></i></a></li>
						<li class="list-inline-item"><a href="javascript:void();"><i class="fa fa-instagram"></i></a></li>
						<li class="list-inline-item"><a href="javascript:void();"><i class="fa fa-google-plus"></i></a></li>
						<li class="list-inline-item"><a href="javascript:void();" target="_blank"><i class="fa fa-envelope"></i></a></li>
					</ul>
				</div>
			</div>
			<div class="row">
				<div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-2 text-center text-white">
					<p class="h6">&copy All right Reversed.<a class="text-green ml-2" href="https://www.sunlimetech.com" target="_blank">THP</a></p>
				</div>
			</div>
		</div>
	</section>

app/views/shared/_header.html.erb
<div class="concert-header jumbotron jumbotron-fluid">
  <div class="container">
    <h1>Vos concerts préférés entre passionné(e)s</h1>
    <br>
    <p class="head-lead">Les concerts en solo ? Forcer vos proches à vous accompagner ? Plus maintenant !</p>
    <br><br>
    <%= link_to 'Accéder aux concerts', concerts_path, class:'header-btn btn btn-lg' %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-dark fixed-top navbar-inverse navbar-expand-lg navbar-custom">
      <%= link_to image_tag("brown-red-logo.png", height: '70px', width: '70px', class:'nav-logo'), root_path %>
      <%= link_to 'Live & Tribe', root_path, class:'navbar-brand' %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample05" aria-controls="navbarsExample05" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExample05">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <% if user_signed_in? %>
            <%= link_to "Profil", users_path(current_user.id), class: "nav-link" %>
            <% end %>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="/concerts">Accéder aux concerts <span class="sr-only">(current)</span></a>
          </li>
        </ul>
        <div class="sign-up-in">

          <% if user_signed_in? %>
            <%= link_to 'Modifier mon profil', edit_user_registration_path, class:'btn-signup' %>
            <%= link_to 'Se déconnecter', destroy_user_session_path, method: :delete, class: 'btn btn-outline-light' %>
          <% else %>
            <%= link_to "S'enregistrer", new_user_registration_path, class: 'btn-signup' %>
            <%= link_to "Se connecter", new_user_session_path, class:'btn btn-outline-light'%>
          <% end %>
        </div>
      </div>
    </nav>

app/views/shared/_navbar2.html.erb
<nav class="navbar navbar-dark bg-secondary fixed-top navbar-inverse navbar-expand-lg">
      <%= link_to image_tag("brown-red-logo.png", height: '70px', width: '70px', class:'nav-logo'), root_path %>
      <%= link_to 'Live & Tribe', root_path, class:'navbar-brand' %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample05" aria-controls="navbarsExample05" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExample05">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <% if user_signed_in? %>
            <%= link_to "Profil", users_path(current_user.id), class: "nav-link" %>
            <% end %>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="/concerts">Accéder aux concerts <span class="sr-only">(current)</span></a>
          </li>
        </ul>
        <div class="sign-up-in">

          <% if user_signed_in? %>
            <%= link_to 'Modifier mon profil', edit_user_registration_path, class:'btn-signup' %>
            <%= link_to 'Se déconnecter', destroy_user_session_path, method: :delete, class: 'btn btn-outline-light' %>
          <% else %>
            <%= link_to "S'enregistrer", new_user_registration_path, class: 'btn-signup' %>
            <%= link_to "Se connecter", new_user_session_path, class:'btn btn-outline-light'%>
          <% end %>
        </div>
      </div>
    </nav>

app/views/shared/_presentation.html.erb
<section class="module divider-bottom">
  <div class="container-fluid homescroll">
    <div class="row">
      <div class="col-md-6 m-auto text-center">
        <h2 class="title-presentation tribu">Rejoins ta tribu</h2>
      </div>
    </div>
    <div class="row situations">
      <div class="col-lg-4 col-md-6">
        <div class="situation text-center">
          <div class="situation-content">
            <p>Aucun de tes proches ne partage tes goûts musicaux et t'accompagner à ton concert relève de la corvée</p>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-6">
        <div class="situation text-center">
          <div class="situation-content">
            <p>Tu as l'intime conviction que des gens aux goûts musicaux singuliers comme toi ne se cachent pas très loin</p>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-6">
        <div class="situation text-center">
          <div class="situation-content">
            <p>Tu veux rejoindre une communautés de fans, les retrouver pour des before, partager des souvenirs</p>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="moto">
        <div class="col-md-8 m-auto text-center catch-phrase">
          <p class="pres-lead">Ne dépendez plus de la motivation de vos proches pour aller voir votre artiste préféré. Plus besoin d'arguments farfelus pour appâter vos amis ! </p>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12 text-center ">
        <h2 class="title-presentation howorking">Comment ça marche ?</h2>
      </div>
    </div>

    <div class="row etapes">
      <div class="col-lg-4 col-md-6">
        <div class="icon-box text-center">
          <div class="icon-box-icon"><span class="music-logo"><%= image_tag("musician (1).png", height: '80px', width: '80px', class:'music-logo') %></span></div>
          <div class="icon-box-title">
            <h6>TROUVEZ VOTRE CONCERT</h6>
          </div>
          <div class="icon-box-content">
            <p>Cliquez sur "accéder aux concerts" et effectuez votre recherche parmi les milliers de concerts proposés dans les 10 plus grandes villes de France. Cliquez sur l'évènement qui vous intéresse.</p>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-6">
        <div class="icon-box text-center">
          <div class="icon-box-icon"><span class="ti-harddrives"></span><%= image_tag("conversation.png", height: '80px', width: '80px', class:'conversation-logo') %></div>
          <div class="icon-box-title">
            <h6>REJOIGNEZ LA DISCUSSION</h6>
          </div>
          <div class="icon-box-content">
            <p>4 chaînes de discussions à votre disposition: "Before", "Trajet", "Les vrais savent", "Debrief". Ne soyez pas timides.</p>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-6">
        <div class="icon-box text-center">
          <div class="icon-box-icon"><span class="rencontres-logo"><%= image_tag("pet.png", height: '80px', width: '80px', class:'rencontres-logo') %></span></div>
          <div class="icon-box-title">
            <h6>ENJOY</h6>
          </div>
          <div class="icon-box-content">
            <p>On n'est pas Tinder, mais ça ne vous empêche pas de faire de belles rencontres autour de vos artistes préférés. ;)</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/shared/_search_by_algolia.html.erb
<%= image_tag("search_by_algolia200px.png", class:'img-fluid algolia-footer', width: '200px', style: 'margin-top:10px') %>

app/views/shared/_searchbar.html.erb
<div class="searchbar-container">
  <div class="searchbar-input">
    <input id="search-input" placeholder="Trouve ton concert" class="form-control">
  </div>
  <main>
    <div id="hits"></div>
    <div id="pagination"></div>
  </main>
  <!-- Include AlgoliaSearch JS Client and autocomplete.js library -->
  <script src="https://cdn.jsdelivr.net/npm/instantsearch.js@2.3/dist/instantsearch.min.js"></script>
  <script type="text/javascript">
  $(document).ready(function() {
    //do work
  var search = instantsearch({
              appId: 'DA0L98N7JW',
              apiKey: '5c1dc777d34fdb7c5cf4bedfdb9ac2bf', // search only API key, no ADMIN key
              indexName: 'ParisConcerts',
              urlSync: true,
              searchParameters: {
                hitsPerPage: 12
              },
            });
            search.addWidget(
              instantsearch.widgets.searchBox({
                container: '#search-input',
                instantsearchPage: function () { return false; },

              })
            );
            search.addWidget(
              instantsearch.widgets.hits({
                container: '#hits',
                templates: {
                  item: document.getElementById('hit-template').innerHTML,
                  empty: "We didn't find any results for the search <em>\"{{query}}\"</em>"
                }
              })
            );
            search.addWidget(
              instantsearch.widgets.pagination({
                container: '#pagination'
              })
            );

            search.start();
  });
  </script>
  <!-- <script src="https://cdn.jsdelivr.net/algoliasearch/3/algoliasearch.min.js"></script> -->
  <!-- <script src="https://cdn.jsdelivr.net/autocomplete.js/0/autocomplete.min.js"></script> -->

  <script type="text/html" id="hit-template">
  <div class = "card-container">
    <div class="card hit">
      <div class="card-img-top" role="img" style="background-image: url(https://images.sk-static.com/images/media/profile_images/artists/{{performance.0.artist.id}}/huge_avatar);">
        <div class="card-artist"></div>
      </div>
      <div class="card-body">
        <h4 class="card-text">{{{_highlightResult.displayName.value}}}</h4><br/>
        <h5 class="card-title">{{location.city}}</h5>
        <a href="/concerts/{{id}}" class="card-btn btn btn-primary btn-lg">Voir l'évènement</a>
      </div>
    </div>
  </div>
  </script>
</div>

app/views/shared/_show-header.html.erb
<div class="show-header">
  <div class="container">
      <h2><%= @artist_name %> - <%= @venue_place %> </h2>
      <p id="date"><i class="fa fa-map-marker" aria-hidden="true"></i> <%= @venue_adress %> - <%= @venue_postal_code %> - <%= @venue_city %> </p>
      <p> <i class="fa fa-calendar-o" aria-hidden="true"></i> Le <%= @venue_date %> à <%= @venue_hour %> </p>
  </div>
</div>